### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by Mujtaba4ahmed** [Autodesk-Forge/forge-rcdb.nodejs#14]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mujtaba.ahmed\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mujtaba.ahmed\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\W&W\forge-rcdb.nodejs-master\node_modules\canvas
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

I am constantly getting this error while doing npm install
Any help please respond ASAP

**Comment by Yaxian** [comment]
It seems `node-canvas` install error. Try [Installation---Windows](https://github.com/Automattic/node-canvas/wiki/Installation---Windows)

**Comment by leefsmp** [comment]
This is a problem with your dev env not the sample itself. I hope the suggestion helps you. I will go ahead and close the issue for now.

**Comment by Mujtaba4ahmed** [comment]
Could you elaborate 'dev env' @leefsmp please?

while installing canvas I am getting the same error:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mujtaba.ahmed\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mujtaba.ahmed\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WINDOWS\system32\node_modules\canvas
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Please help me out here.

**Comment by Yaxian** [comment]
```
OS: Mac Sierra
Platform: Linux
```

**Comment by Mujtaba4ahmed** [comment]
OS: Windows

**Comment by Yaxian** [comment]
you could ignore this error.
