### ISSUE TITLE
Error while processing SVF: {"url":"http://localhost:3000/resources/models/dev/engine/0.svf","httpStatus":404,"httpStatusText":"Not Found"}

### ISSUE THREAD

**Issue by Mujtaba4ahmed** [Autodesk-Forge/forge-rcdb.nodejs#16]
why am I getting this error while running the app.

Error while processing SVF: {"url":"http://localhost:3000/resources/models/dev/engine/0.svf","httpStatus":404,"httpStatusText":"Not Found"}

There is no /resources/models/dev folder in the project. And it is looking for the 0.svf file which isn't there. 
Please respond asap.
Thanks.

**Comment by Mujtaba4ahmed** [comment]
It is quiet urgent. If anyone has any solution to this please respond asap. @leefsmp

**Comment by leefsmp** [comment]
This is a local resource that I am using for testing purpose only, I don't see how this can affect your own development. This resource is simply not provided with the sample. You will have to populate the database with your own local resources and translated files. 

If you just starting with Forge and the viewer, I would recommend you get some experience with a less complex sample, like for example [forge-react-boiler.nodejs](https://github.com/Autodesk-Forge/forge-react-boiler.nodejs), which doesn't require much set up of your dev environment.

**Comment by Mujtaba4ahmed** [comment]
I will look into it. Am I facing that error because I do not have those '0.svf' files ?

I just want to run the app with those existing models itself.

**Comment by leefsmp** [comment]
Yes, there are no files committed on the repo with that project. The project is provided for the code not as a library for models. You can use any model that you translated yourself on Forge. If you don't know how to translate a model take a look at [Prepare a File for the Viewer](https://developer.autodesk.com/en/docs/model-derivative/v2/tutorials/prepare-file-for-viewer/), alternatively you can use [models.autodesk.io](https://models.autodesk.io/). To perform extraction and offline viewing take a look at that [article](https://forge.autodesk.com/blog/forge-svf-extractor-nodejs).

**Comment by Mujtaba4ahmed** [comment]
If I have the model urn then '.svf' file is not required. is it correct?

**Comment by leefsmp** [comment]
correct, `the standard`way is to load the models from the Autodesk Cloud, by providing an URN and a token as described in the documentation, but you can also download locally all the required resources and load the models offline or choose to host those resources on your own server, in which case you would lost some benefits such as being able to query/export the data using [Model Derivatives API](https://developer.autodesk.com/en/docs/model-derivative/v2/overview/). Hope that helps.

**Comment by Mujtaba4ahmed** [comment]
Thanks.
In the model schema we are providing both 'urn' and 'path' in there. I changed the urn with the urn of my model, but it is still asking for that path(/resource/model/dev/.......). Why am I seeing this error(404) still?

**Comment by Mujtaba4ahmed** [comment]
I downloaded the model files to my local repo and it is working now. Although I do not understand why providing the urn does not work in my project. 

Can I integrate my project with SQLServer DB instead of MongoDB? Would that take lot of effort shifting the app to sqlserver?
Thanks.

**Comment by leefsmp** [comment]
When loading by URN you need to set `"env": "AutodeskProduction"`, take a look at this article for more details: [Working seamlessly online/offline when developing your Web applications with the Forge Viewer](https://forge.autodesk.com/cloud_and_mobile/2016/10/working-seamlessly-onlineoffline-when-developing-apps-with-the-forge-viewer-.html). 

I can't really tell you how much effort it would be shifting to SQL, probably a fair amount of changes on the server side. The app is fragmented into a lot of independent demos, most of the database part is specific to each demo, so it depends the scope of your own app...

**Comment by Mujtaba4ahmed** [comment]
I appreciate your help Philippe. Thanks.
If you could give me something to start off with while changing the DB to SQL, it would be great. 
Area of code in the app that would require changes for it to integrate it with SQL. Also, are there any Location id's for each element in the model that are in realtion with the data in DB?
Thanks.

**Comment by leefsmp** [comment]
Hot Reload is already in place for `development` env. I can't decently enumerate the list of all the changes you would need to do in order to migrate the whole sample from Mongo to SQL. Please take a closer look at the server code.

**Comment by Mujtaba4ahmed** [comment]
Is it even possible to integrate SQL server with this app instead of MongoDB?
Any help is appreciated.
Thanks.

**Comment by Mujtaba4ahmed** [comment]
If you could mention briefly about components that might need changes, that would be of great help.
Thanks Philippe.
