### ISSUE TITLE
compile the project failed on windows10

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#19]
I am trying to compile the project on my windows10
then stop with error running "npm install"

![2017-09-27_15-20-07](https://user-images.githubusercontent.com/9555002/30900662-6a844016-a397-11e7-991e-2c27e219c69e.png)

I did install the SDK10

**Comment by leefsmp** [comment]
Probably same as [here](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/issues/14). This is a problem with your dev env not the project itself.

**Comment by ruixiwu** [comment]
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

D:\_h5_work\forge-rcdb.nodejs0927>npm install

> canvas@1.6.7 install D:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas
> node-gyp rebuild


D:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas>if not defined npm_config_node_gyp (node "D:\programfiles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\b
in\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
  win_delay_load_hook.cc
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\ImageData.cc) [D
:\_h5_work\for
ge-rcdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\CanvasPattern.cc
) [D:\_h5_work
\forge-rcdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\init.cc) [D:\_h5
_work\forge-rc
db.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\Image.cc) [D:\_h
5_work\forge-r
cdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\CanvasGradient.c
c) [D:\_h5_wor
k\forge-rcdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\Canvas.cc) [D:\_
h5_work\forge-
rcdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
d:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\src\Canvas.h(19): fatal error C1083: 无法打开包括文件: “cairo.h”: No such file or directory (编译源文件 ..\src\CanvasRenderingC
ontext2d.cc) [
D:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\programfiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\ProgramFiles\\nodejs\\node.exe" "D:\\programfiles\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\_h5_work\forge-rcdb.nodejs0927\node_modules\canvas
gyp ERR! node -v v6.11.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-ga@2.3.4 requires a peer of prop-types@^15.5.10 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 (node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

D:\_h5_work\forge-rcdb.nodejs0927>npm start

> forge-rcdb@4.0.0 start D:\_h5_work\forge-rcdb.nodejs0927
> node bin/start.js

fs.js:953
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\_h5_work\forge-rcdb.nodejs0927\dist'
    at Error (native)
    at Object.fs.readdirSync (fs.js:953:18)
    at findAllCompressionFiles (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\express-static-gzip\index.js:127:24)
    at expressStaticGzip (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\express-static-gzip\index.js:28:9)
    at Object.<anonymous> (D:/_h5_work/forge-rcdb.nodejs0927/src/server/index.js:230:11)
    at Module._compile (module.js:570:32)
    at loader (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\_h5_work\forge-rcdb.nodejs0927\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\bin\start.js:24:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\programfiles\\nodejs\\node.exe" "D:\\programfiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! forge-rcdb@4.0.0 start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-rcdb@4.0.0 start script 'node bin/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forge-rcdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forge-rcdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forge-rcdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_h5_work\forge-rcdb.nodejs0927\npm-debug.log

D:\_h5_work\forge-rcdb.nodejs0927>

**Comment by ruixiwu** [comment]
build failed, start failed also

**Comment by ruixiwu** [comment]
I work with vs2015 and installed windows sdk 8.1
