### ISSUE TITLE
how to set the Client ID and Client Secret for this project?

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#23]
sorry, I am a total new guy, 
when I started the  server (no db connected), and the go to the  "localhost:3000" in chrome.
I try to login , the the browser throw an error like this:
![2017-09-29_1-33-42](https://user-images.githubusercontent.com/9555002/30981456-fd271f18-a4b6-11e7-9aa5-6cd4ed9585a0.png)
I did applied the client ID for my app in the forge platform:
![2017-09-29_1-34-45](https://user-images.githubusercontent.com/9555002/30981524-375cf8ec-a4b7-11e7-81a2-7d562324c230.png)

My question is : where to set the client ID and Client Secret for the project with my personal forge key?

**Comment by leefsmp** [comment]
You need to define the following environment variable or hardcode them in the config file, which is not recommended:

`FORGE_DEV_CLIENT_ID="your_client_id"`
`FORGE_DEV_CLIENT_SECRET="your_client_secret"`
`NODE_ENV=development`

Please take a look at a simpler project first, this one [forge-react-boiler.nodejs](https://github.com/Autodesk-Forge/forge-react-boiler.nodejs) has a setup that is much more friendly, I doubt that deploying that complex project will help you much understand how forge APIs are working...

**Comment by ruixiwu** [comment]
thanks very much
