### ISSUE TITLE
upload rvt file failed and stopping at 50%

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#25]
Hello, all, 

I am uploading a file , then the system stoppping at 50% all the time.
is that a normal behave?
![2017-09-30_22-49-34](https://user-images.githubusercontent.com/9555002/31046806-364c6fe2-a632-11e7-957e-8d0e6a840608.png)

**Comment by ruixiwu** [comment]
webpack: Compiled successfully.
Socket connected: ZAiZYl208rPujSDFAAAA
Socket disconnected: ZAiZYl208rPujSDFAAAA
Socket connected: -d6MitsZ-HEW5bAsAAAB
Socket disconnected: -d6MitsZ-HEW5bAsAAAB
Socket connected: aj1bEv6k_aZmN0ZNAAAC
Cleaning Dir: D:\_h5_work\forge-rcdb.nodejs0927\TMP
Cleaning Dir: D:\_h5_work\forge-rcdb.nodejs0927\TMP
Cleaning Dir: D:\_h5_work\forge-rcdb.nodejs0927\TMP
{ Error: EPERM: operation not permitted, stat 'D:\_h5_work\forge-rcdb.nodejs0927\TMP\75b528969c33f0bd3889cefe6ef1cc08.rvt'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'D:\\_h5_work\\forge-rcdb.nodejs0927\\TMP\\75b528969c33f0bd3889cefe6ef1cc08.rvt' }
Socket disconnected: aj1bEv6k_aZmN0ZNAAAC
Socket connected: 68_b0NpPQTi-WCUiAAAD
Cleaning Dir: D:\_h5_work\forge-rcdb.nodejs0927\TMP
{ Error: EPERM: operation not permitted, stat 'D:\_h5_work\forge-rcdb.nodejs0927\TMP\75b528969c33f0bd3889cefe6ef1cc08.rvt'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'D:\\_h5_work\\forge-rcdb.nodejs0927\\TMP\\75b528969c33f0bd3889cefe6ef1cc08.rvt' }
Socket disconnected: 68_b0NpPQTi-WCUiAAAD
Socket connected: 1sO-jHTiZlJFebg4AAAE
Socket disconnected: 1sO-jHTiZlJFebg4AAAE
Socket connected: 2j9iYc0pKlHSBgfGAAAF
Cleaning Dir: D:\_h5_work\forge-rcdb.nodejs0927\TMP
{ Error: EPERM: operation not permitted, stat 'D:\_h5_work\forge-rcdb.nodejs0927\TMP\75b528969c33f0bd3889cefe6ef1cc08.rvt'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'D:\\_h5_work\\forge-rcdb.nodejs0927\\TMP\\75b528969c33f0bd3889cefe6ef1cc08.rvt' }
Socket disconnected: 2j9iYc0pKlHSBgfGAAAF

**Comment by ruixiwu** [comment]
did any one has suffered the same issue?

**Comment by leefsmp** [comment]
My first guess is that you didn't change the `bucketKey` in the [config](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/config/development.config.js#L27), so your server is trying to upload to a Forge bucket that I have created under my account. Make sure you define a bucketKey that is unique. Keep in mind bucketKeys have to be unique service-wide, so don't use a basic name such as `bucket1`, also no special characters. You can append your `clientId` to the bucketKey for example.

**Comment by ruixiwu** [comment]
hello, leefsmp,
I try to change the bucketID alternatively, but failed
should I apply an OSS something first to get my bucket space and then to upload the rvt file there? but I don't know where to apply the OSS?

![2017-10-01_16-57-16](https://user-images.githubusercontent.com/9555002/31053208-e76c6bd6-a6ca-11e7-8753-7455083f15ce.png)

Ricky

**Comment by ruixiwu** [comment]
hello, leefsmp, 
I did created an bucket, and make a new bucketkey for gallery:
![2017-10-01_21-48-08](https://user-images.githubusercontent.com/9555002/31055262-1156b582-a6f3-11e7-99f4-49002d8d141e.png)

then I "npm start " again with that new bucketkey
it seems the system upload the file to oss successfully, but translated the model failed and keeping at 0% all the time:
![2017-10-01_21-51-08](https://user-images.githubusercontent.com/9555002/31055337-f214ceba-a6f3-11e7-9b89-0d93c302393f.png)



My question:
what's the bucket  for the following meta script in config file? do I need to create another bucket for the meta?
  
  meta: {
    bucket: {
      bucketKey: 'ricky-metabucket',
      policyKey: 'Persistent'
    }
  },

**Comment by ruixiwu** [comment]
hello, leefsmp, 

the system upload and translate the rvt file successfully, 
the original is revit 2012 version, it seems too old;  I opened the rvt file with revit2018 and save it and then upload it again.

![2017-10-01_22-42-18](https://user-images.githubusercontent.com/9555002/31055753-2383e7fa-a6fa-11e7-8b14-95b37134519e.png)

**Comment by leefsmp** [comment]
Did you try without chinese characters in the filename?

**Comment by ruixiwu** [comment]
hello, leefsmp, 
I have uploaded the new renamed file without chinese characters. 
it acts the same as before.

and I tested the behavior in "https://forge-rcdb.autodesk.io/gallery" with the same file. it works well.

so it's strange.

**Comment by ruixiwu** [comment]
by the way,  there is nothing to show  in the configurator page and main page. 
I am wondering how to config those items like ""https://forge-rcdb.autodesk.io" ?
is that normal behavior by default at the beginning?

![2017-10-02_13-19-08](https://user-images.githubusercontent.com/9555002/31065187-17302bf4-a776-11e7-8fb9-d0704b854bb2.png)
![2017-10-02_13-18-56](https://user-images.githubusercontent.com/9555002/31065196-2273fa36-a776-11e7-833f-a82aec272cf0.png)
