### ISSUE TITLE
npm start failed in production mode

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#29]
npm run build-prod ----> successfully
but npm start failed, the server say:

D:\_h5_work\forge-rcdb.nodejs0927  (forge-rcdb@4.0.0)
λ npm start

> forge-rcdb@4.0.0 start D:\_h5_work\forge-rcdb.nodejs0927
> node bin/start.js

module.js:471
    throw err;
    ^

**Error: Cannot find module './static'**
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_h5_work\forge-rcdb.nodejs0927\bin\start.js:15:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\programfiles\\nodejs\\node.exe" "D:\\programfiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! forge-rcdb@4.0.0 start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the forge-rcdb@4.0.0 start script 'node bin/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the forge-rcdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs forge-rcdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls forge-rcdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_h5_work\forge-rcdb.nodejs0927\npm-debug.log

What is static module?? there is no such a module in the source.
How to do?

**Comment by leefsmp** [comment]
you need to run command `npm run build-server` in order to build the static server

**Comment by ruixiwu** [comment]
thanks leefsmp
