### ISSUE TITLE
IE-11 browser support

### ISSUE THREAD

**Issue by srinivas-mallisetty** [Autodesk-Forge/forge-rcdb.nodejs#31]
We are seeing blank page we browse the https://forge-rcdb.autodesk.io/ in ie11

Is there any way to make it work on IE-11?

**Comment by leefsmp** [comment]
I did not bother supporting such clunky browser, sorry about that. I know it may still be a corporate standard in some companies but this is a browser from another era. I will not invest any efforts supporting it, sorry for the bad news.
