### ISSUE TITLE
Don't know how to setup the project

### ISSUE THREAD

**Issue by gyber** [Autodesk-Forge/forge-rcdb.nodejs#40]
HI
Thanks for creating this great project. I wanted to figure out how to use the various cool extensions in the project but failed in the first step... And I also want to know that if I setup correctly, will there be any samples with extensions in the configurator?

------------------------------------------------------------------

I downloaded and ran 
```
npm install
set NODE_ENV=development
set HOT_RELOADING=true
set FORGE_DEV_CLIENT_SECRET=xxx
set FORGE_DEV_CLIENT_ID=xxx
npm start
```

But when I opened http://localhost:3000, it was empty (the UI appeared but there were no models) and the console showed:

Failed to load resource: the server responded with a status of 404 (Not Found) :3000/api/forge/user
or
GET http://localhost:3000/api/forge/user 404 (Not Found)

![pic2](https://user-images.githubusercontent.com/30907919/35024652-a10016e2-fb7b-11e7-8030-78040b7219a6.PNG)

----------------------------------------------------------------
It had been like this. 

![pic3](https://user-images.githubusercontent.com/30907919/35024847-bf3c10c4-fb7c-11e7-94a2-b5674e5e5c07.PNG)

I changed \config\development.config.js and loaded three.js, viewer3D.js and style.css. (I changed nothing else)
But I still couldn't setup the project. 

Did I do anything wrong?

**Comment by leefsmp** [comment]
So the 404 error is expected as you are not logged in (upper-right corner, use your forge account for that).

Then the models are being loaded from the database, so are you running a local mongoDB and did you populate a collection named "rcdb.models" that looks like the one there:
[https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/resources/db/dev/rcdb.models.json](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/resources/db/dev/rcdb.models.json)

You will also need to either use your own [online models](https://developer.autodesk.com/en/docs/model-derivative/v2/tutorials/prepare-file-for-viewer/) and change "Local" to "AutodeskProduction", then update the urn field, see that article: 
[Working seamlessly online/offline when developing your Web applications with the Forge Viewer](https://forge.autodesk.com/cloud_and_mobile/2016/10/working-seamlessly-onlineoffline-when-developing-apps-with-the-forge-viewer-.html)

Or translate and download viewables, which can be done from the /gallery section once you uploaded your models there:

![screen shot 2018-01-17 at 07 57 50](https://user-images.githubusercontent.com/4352502/35029662-3a987b0c-fb5c-11e7-8a67-098236b41998.png)

Hope that helps.
