### ISSUE TITLE
Could you please share the offline model resource of IOT ? 

### ISSUE THREAD

**Issue by ccyyiiooo** [Autodesk-Forge/forge-rcdb.nodejs#41]
Hi leefsmp,
I am trying to set up the IOT example,but the model does not display properly.
![qq 20180125233757](https://user-images.githubusercontent.com/7933245/35396867-d2ffd0b6-0228-11e8-86b1-d092115697c9.jpg)
Could you please share the offline model resource of IOT ? 
Thanks for your attention, I am looking forward to your early reply.

**Comment by leefsmp** [comment]
The model doesn't display because you need to replace in the database the URN of a model translated with your Forge account. I cannot share the seed files with you for that sample. But the demo will run with any other model as long as you update the position of the hotspots in the database.

**Comment by PavelBalobanov** [comment]
Pl

> The model doesn't display because you need to replace in the database the URN of a model translated with your Forge account. I cannot share the seed files with you for that sample. But the demo will run with any other model as long as you update the position of the hotspots in the database.

Please, Let me know how to do this?
