### ISSUE TITLE
How to implement this in .net

### ISSUE THREAD

**Issue by tinygeek101** [Autodesk-Forge/forge-rcdb.nodejs#44]
Is der any other example or any other way to implement it using .net , as i m new to node.js

**Comment by leefsmp** [comment]
Please refer to our [.Net SDK samples](https://developer.autodesk.com/en/docs/quickstarts/v1/overview/) and other [C# samples that we have on that github organization](https://github.com/Autodesk-Forge?utf8=%E2%9C%93&q=&type=&language=c%23)
