### ISSUE TITLE
Not able to run on dev env

### ISSUE THREAD

**Issue by amanpareek93** [Autodesk-Forge/forge-rcdb.nodejs#45]
http://localhost:3000/
says 
Cannot GET /

Console:
NODE_ENV=development npm start
> node bin/start.js
Server listening on PORT: 3000
ENV: development
Connected to MongoDB Database: forge-rcdb
Cleaning Dir: /Users/aman/forgetest/forge-rcdb.nodejs/TMP

No error in console as well.

**Comment by leefsmp** [comment]
Need to add HOT_RELOADING=true for dev env, not mentioned in the instructions, sorry.
