### ISSUE TITLE
Markups disappear when zooming in

### ISSUE THREAD

**Issue by Keorl** [Autodesk-Forge/forge-rcdb.nodejs#47]
Hi,

There is an issue I have, which also happens on the [live demo](https://forge-rcdb.autodesk.io/configurator?id=5a361b2b58144b5ed2936ddf&_ga=2.76732566.2055104968.1519641037-718053475.1517216874).
When you zoom too close to one or several marks, they are not rendered anymore.
In my own implementation, I don't use user interaction and use code to place marks inside a big building model. The marks disappear when I zoom too close to the building, which is long before I am inside near whatever objects are marked.

Is there any way to work around this ?

**Comment by leefsmp** [comment]
After reading [that](https://stackoverflow.com/questions/38728563/fix-disappearing-points-in-three-js-pointcloud) I added the following code which seems to fix the issue:
```
// creates THREE.PointCloud
this.pointCloud = new THREE.PointCloud(
  this.geometry, this.shader.material)

this.pointCloud.frustumCulled = false
```
