### ISSUE TITLE
Model load forever

### ISSUE THREAD

**Issue by albertotono** [Autodesk-Forge/forge-rcdb.nodejs#48]
dear Philippe,
I have a model in Revit2016 about 450MB I uploaded on my A360 and I am not able to visualize it here in RCDB. Also when I try to create New Scenes for VR/AR it keeps load forever, could you please point me in the right direction?!
Thanks a lot for your attention

**Comment by arif-hanif** [comment]
i am having similar problems with large models, the upload completes but it gets stuck in processing to convert over to 3d view.

**Comment by albertotono** [comment]
Yes, I am able to load in A360 Directly. I tried both, custom and another app. (Ps: that link gives me 502Bad Request). And No error in the console. 

Arif, the best solution is to upload the file in the Sample Bucket at the moment. But with a large project doesn't seem to be able to open the VR scene right now. When we download in Unity if it takes more than one hour and the token Expire before the end what is going to happen?!

**Comment by leefsmp** [comment]
Nothing directly related to this specific project, I'm closing this issue for the time being.
