### ISSUE TITLE
Forge and iot

### ISSUE THREAD

**Issue by Nik1990** [Autodesk-Forge/forge-rcdb.nodejs#50]
Hi guys, i need some helps.
I need to understend the powers of forge and iot. So, where is the best way to take some measure from real building (es arduino that send data to database X) and allow viewer of forge to read this data?
I have for exemple a IFC model, is the ifc that shuld containe IFCSensora and DB source? My target is a project similar to this:

https://forge-rcdb.autodesk.io/configurator?id=58adee163e6f342cf1e92dae

1 -  Where are defined the sensors dots?
2 - It's an IFC file that?
3 -  Which db are supported?
4 - How can i link the dots with the source datastream?
5 -  Ho can find more docs/example about this?

Thanks a lot!

**Comment by leefsmp** [comment]
There is nothing IoT specific coming with Forge. Typically you would have IoT data coming from some sensors, the data gets send to your own server and your client app can access this data. No Forge involved in the whole process. Now you can use some client-side customization to represent that data in the viewer, as illustrated by the sample you pointed out. Wether the position of the sensors is defined in your model or not is really up to you. The source of that demo is available at  [Viewing.Extension.IoT](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/tree/master/src/client/viewer.components/Viewer.Extensions.Dynamic/Viewing.Extension.IoT).

**Comment by Nik1990** [comment]
Ok thanks, and in this specific example (Viewing.Extension.IoT) the sensors are defined in the model or not? There are examples of models that defines sensors insides?

Thanks

**Comment by leefsmp** [comment]
There is no "doc" about it, as mentioned the whole demo is a custom implementation, you need to look at the code to see how it is implemented. In this specific demo the markups are implemented as html overlays. You can also refer to those articles for different approaches: [High-Performance 3D markups with PointCloud in the Forge Viewer](https://forge.autodesk.com/blog/high-performance-3d-markups-pointcloud-forge-viewer) and [3D Markup with icons and Info-Card](https://forge.autodesk.com/blog/3d-markup-icons-and-info-card). The sensor "data" is just the 3d coordinates where should appear each markup, this can be defined either in the model as properties (which you could access with viewer.getProperties(dbId)) or in a side database, or provided by your own endpoint exposed by your server, ...
