### ISSUE TITLE
The clicking model is always ready to enter the model when it is ready to enter. It has been displayed on loading. There is no right to report errors.

### ISSUE THREAD

**Issue by changjiang2** [Autodesk-Forge/forge-rcdb.nodejs#54]
![jygh qve9pp1t b oy c 3f](https://user-images.githubusercontent.com/39937108/45464231-3c2b5f00-b742-11e8-9423-b22eb53c1d8d.png)
![jllpy rfc4f9oi x 2je0b](https://user-images.githubusercontent.com/39937108/45464235-42214000-b742-11e8-958e-e01e6d08dbba.png)

**Comment by dukedhx** [comment]
读取在线模型时需要登入
