### ISSUE TITLE
No access token is provided

### ISSUE THREAD

**Issue by astrolabio** [Autodesk-Forge/forge-rcdb.nodejs#57]
When accesing the models the console gives the error:
"No access token is provided, but authorization requested. This is a problem."

But the viewer lets you continue viewing it. ¿Why?

In the code the accesstoken parameter is commented out.

`        const viewerEnv = await this.initialize({
          useConsolidation: true,
          env: dbModel.env,
          // getAccessToken: function(onGetAccessToken) {
          //   onGetAccessToken(accessToken, expireTimeSeconds)
          // }
        }) `

**Comment by cyrillef** [comment]
This is curious - did you clear you cache?

**Comment by astrolabio** [comment]
![captura](https://user-images.githubusercontent.com/4153350/46398123-8924a480-c6f4-11e8-99f6-3ece3b8afd71.PNG)
The Cache is disabled

**Comment by cyrillef** [comment]
Since you are on forge-rcdb live, I believe you did not login using your account/credentials, and you get this error. But this error has nothing to do with the model you are currently viewing. This model is public, and does not require login, hence you can see it.

**Comment by astrolabio** [comment]
If I log in the first error dissapear but the second is related to the viewer

**Comment by cyrillef** [comment]
can you copy me the url you are using when you see this error?

**Comment by astrolabio** [comment]
https://forge-rcdb.autodesk.io/database?id=583ec7efebfb320e3cef26a5

**Comment by cyrillef** [comment]
ok, this is what I said above this model is public, so there is no need of a token. Actually the code obfuscate the real token itself being a proxy. On your debugger console, enter the following line of code:
NOP_VIEWER.model.myData.basePath

note the syntax of the URL  -> lmv-proxy-2legged

When doing this, the token will be added by the RCDB server to any HTTP request coming from the Viewer - this is a security measure to prevent someone from using the real token to access any information other than the one we allow.

**Comment by astrolabio** [comment]
Yes, but if you make the page private but someone knows the urn of your model, he will be able to access your model through his viewer, isn't it?

**Comment by leefsmp** [comment]
Yes as long as he has access to a valid access token with viewable scope, which can be exposed by an endpoint of your app. To prevent that you can use a proxy as mentioned above and enforce that kind of permission at the proxy level, typically you can add any extra custom logic in the proxy that could check if currently logged user is allowed to view the model pointed by requested URN.
