### ISSUE TITLE
GET / 404 on Heroku

### ISSUE THREAD

**Issue by fredpolicarpo** [Autodesk-Forge/forge-rcdb.nodejs#65]
Hello,

When I deploy to Heroku, a have the folling error:

`Cannot GET /`

The error on heroku log is:

`2019-02-02T18:04:31.494157+00:00 heroku[router]: at=info method=GET path="/" host=bim-explorer.herokuapp.com request_id=03ffff27-6b39-4c13-8bbd-de1d76873ca7 fwd="170.254.135.152" dyno=web.1 connect=1ms service=1495ms status=404 bytes=641 protocol=https
`

My Procfile is:
`web: npm run build-server && NODE_ENV=production npm start`

And Heroku says that the deplay wass success.

**Comment by dukedhx** [comment]
You need to build the client as well - use the `remastered` version which has a simpler build process
