### ISSUE TITLE
Cannot read property 'texture' of null

### ISSUE THREAD

**Issue by Reems59** [Autodesk-Forge/forge-rcdb.nodejs#66]
Hi all ! 
Do you know what is the problem ? 
![screenshot_20190214_115047](https://user-images.githubusercontent.com/10403710/52782303-02db8000-304f-11e9-9687-5fc7633363ae.png)
Thanks for help

**Comment by dukedhx** [comment]
Make sure the div container that Viewer is initialized with is attached to DOM and visible at the moment Viewer attempts to load the model and render the scene.
