### ISSUE TITLE
Dual Viewer extention

### ISSUE THREAD

**Issue by npeditto** [Autodesk-Forge/forge-rcdb.nodejs#67]
Hi @leefsmp ,

thank you for you demo! I have a doubt...

I'm new about Forge development so I followed some tutorials like these:
- http://learnforge.autodesk.io/#/tutorials/viewmodels
- https://forge.autodesk.com/en/docs/viewer/v2/tutorials/basic-application/

I understood (I hope :) ) the approach to devel a Viewer Application and how to use the API/SDK. 

Now I would like to import in my Viewer Application your Dual Viewer Extention ([link](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/tree/master/src/client/viewer.components/Viewer.Extensions.Dynamic/Viewing.Extension.DualViewer)) that i saw in this [demo](https://forge-rcdb.autodesk.io/configurator?id=57f3739777c879f48ad54a44) and [here](https://forge-rcdb.autodesk.io/configurator?id=58c7ae474c6d400bfa5aaf37).

I noticed the approach followed in the Forge tutorials are different from the Extentions that I find in the demos ([forge-rcdb.nodejs)](https://github.com/Autodesk-Forge/forge-rcdb.nodejs).

PS I'm developing my App in nodejs/javascript/html.

Could you suggest me how to import that kind of extentions in a Viewer Application (as showed in the official Forge tutorials)?

Nicola

**Comment by dukedhx** [comment]
Follow the tutorials [here](https://forge.autodesk.com/en/docs/viewer/v7/developers_guide/overview/), [here](https://forge.autodesk.com/en/docs/viewer/v7/developers_guide/viewer_basics/extensions/) and [here](https://learnforge.autodesk.io/#/tutorials/extensions)
