### ISSUE TITLE
A stupid question: obviously the import syntax is error , why it  works still???

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#69]
Hello, everyone, 

 I know a little about javascript. I don't understand why the importing syntax works still here ???
Obviously, I think the import external module with wrong path. but why it works still???

![import](https://user-images.githubusercontent.com/9555002/54874322-1d5e0180-4e24-11e9-871c-3a46409a6dd9.png)

Here, I think shoule write like this: 

import ServiceManager from '**../Services/SvcManager**'

![source](https://user-images.githubusercontent.com/9555002/54874325-2353e280-4e24-11e9-9fc5-cc7ce1ce7c9b.png)

**Comment by ruixiwu** [comment]
Did you anyone tell me why it works here??

**Comment by Yaxian** [comment]
the `resovle path` set in webpack config files

**Comment by ruixiwu** [comment]
@Yaxian   thanks,  could you please explain it more clearly or give me some web links about how "resolve path" make the external imported module works right ?

**Comment by ruixiwu** [comment]
@Yaxian  is that mean I just need to right like  this:   import "ExternalModuleXXX"
and then webpack help to find where is the right  ExternalModuleXXX.js file???

but in this project, there are two  SvcManager.js files,   one is  src/client/services/SvcManager.js , the other is src/server/api/services/SvcManager.js.  so which one is the right resolve path here?? I guess it's src/client/services/SvcManager.js  but not sure , and I don't know why like this..

anyway, I feel strange and undetermined about  the path.

is there any more detail docs?

**Comment by ruixiwu** [comment]
@Yaxian 
您好， 起作用的是下面这些个配置？那src/server/api/services/SvcManager.js  是没有用的啦 ？
resolve: {
    modules: [
      path.resolve('./src/client/viewer.components/Viewer.Extensions.Dynamic'),
      path.resolve('./src/client/viewer.components/Viewer.Extensions'),
      path.resolve('./src/client/viewer.components/Viewer.Commands'),
      path.resolve('./src/client/viewer.components'),

      path.resolve('./src/client/components/UIComponents'),
      path.resolve('./src/client/components'),
      path.resolve('./src/client/services'),
      path.resolve('./src/client/styles'),
      path.resolve('./node_modules'),
      path.resolve('./src/client')
    ],
    extensions : ['.js', '.jsx', '.json']
  },

**Comment by Yaxian** [comment]
yeah, the webpack will resolve and compile recursively according to the path in `resolve path` filed. So it will not import files in `src/server` automatically. If you want to import files in `src/server`, you can import these files manually, like  `import xxx from '../../../src/server/api/serivces/Svcmanager`.

**Comment by dukedhx** [comment]
> 您好， 起作用的是下面这些个配置？那src/server/api/services/SvcManager.js 是没有用的啦 ？
对，有关`webpack path resolve`可以参考: http://xabikos.com/2015/10/03/Webpack-aliases-and-relative-paths/，讲的比较透彻了
而`ServiceManager`是管理运行时中的服务，可编译时无关，我们这个例子的架构其实不怎么值得参考嗯
