### ISSUE TITLE
DbIds to isolateFull

### ISSUE THREAD

**Issue by SelaO** [Autodesk-Forge/forge-rcdb.nodejs#7]
in: https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/dfc9e078fde11159d375beb50daab1ce62fcbda4/src/client/viewer.components/Viewer.Extensions.Dynamic/Viewing.Extension.PlantFactory/PropertyPieChart.js#L34

Where does it gets the dbids data from? 

I see the data prop is set like this: https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/ede02dfaf1d753266ac173724bb40f25aab13401/src/client/viewer.components/Viewer.Extensions.Dynamic/Viewing.Extension.PlantFactory/Viewing.Extension.PlantFactory.js#L208

But where is that data extracted from the model? Is there a {"property name" : dbid} map?

**Comment by leefsmp** [comment]
The dbIds are grouped by categories by custom code in parent component:


https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/dfc9e078fde11159d375beb50daab1ce62fcbda4/src/client/viewer.components/Viewer.Extensions.Dynamic/Viewing.Extension.PlantFactory/Viewing.Extension.PlantFactory.js#L427

________________________________
