### ISSUE TITLE
there is no data in Database and cost Breaddown,    always loading 

### ISSUE THREAD

**Issue by kingov** [Autodesk-Forge/forge-rcdb.nodejs#74]
there is no data in Database and cost Breakdown, always loading

![forge2](https://user-images.githubusercontent.com/18070062/58454669-bde8de80-8151-11e9-98e7-8c73fb71cb9a.png)

**Comment by dukedhx** [comment]
Be sure to use a model that contains compliant material data - you can use a working one from the https://forge-rcdb.autodesk.io - download all the files with a browser extension
