### ISSUE TITLE
‘NODE_ENV’ is not recognized as an internal or external command operable program or batch file

### ISSUE THREAD

**Issue by marty3747** [Autodesk-Forge/forge-rcdb.nodejs#77]
I am doing a project. Here is my project procedure:
1. `npm install`
2. `NODE_ENV = development HOT_RELOADING = true npm start`
3. open [http: // localhost: 3000] (http: // localhost: 3000)

When I get to point 2, an error occurs:

‘NODE_ENV’ is not recognized as an internal or external command operable program or batch file

Please help me solve this problem.

**Comment by leefsmp** [comment]
If you run on windows I think you need to do a `set NODE_ENV=development`...

**Comment by marty3747** [comment]
Thank's so much!

**Comment by leefsmp** [comment]
Cool, looks like you may close the issue.
