### ISSUE TITLE
 I do not understand what needs to be done in this line

### ISSUE THREAD

**Issue by marty3747** [Autodesk-Forge/forge-rcdb.nodejs#78]
Can you please tell me what is required in this instruction line. Thx
"Assign all environment variables as required in `config/production.config.js`"

**Comment by leefsmp** [comment]
Check all required environment variables in `config/production.config.js` (those are the `process.env.XXX_SOMETHING_XXX`) and make sure those are defined in the production environment you are running the server app.

**Comment by marty3747** [comment]
@leefsmp 
I run the server in the root folder of the project, through the node.js console. How exactly should be called and exactly where the file is stored in which you need to check for the presence of field fields as in the file C: \ Users \ User \ Desktop \ forge-rcdb.nodejs-master \ config \ production.config.js

**Comment by marty3747** [comment]
@leefsmp 
Look at this file, do i need to make changes to it?
![Screenshot_1](https://user-images.githubusercontent.com/52569199/61057208-76ff3180-a3fd-11e9-83e6-253002de2cf8.png)

**Comment by marty3747** [comment]
@leefsmp 
Or do me need to make changes here?
![image](https://user-images.githubusercontent.com/52569199/61058238-81bac600-a3ff-11e9-91a6-23a06906b97b.png)

**Comment by marty3747** [comment]
I correctly defined the environment variables?
![image](https://user-images.githubusercontent.com/52569199/61060519-53d78080-a403-11e9-9481-e6bde2bf8ea2.png)

**Comment by libvarun** [comment]
Hi marty,

You can read about Environment variables [here](https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786)
It appears you joined git recently and you're new to web development.
This repo is complex for a beginner, it includes too many libraries.

Let me know what you want to achieve using forge, i can guide you to a simple forge sample app.

**Comment by marty3747** [comment]
@libvarun 

Hello! If I understand you correctly, I can say the following: I want to launch a project, the instructions for which are described here. I want to see a project running on the server http: // localhost: 3000, but I have errors that I don’t understand how to solve. If required, I can describe the errors that I have below by attaching a screenshot
