### ISSUE TITLE
 What is the difference between the instruction under the line

### ISSUE THREAD

**Issue by marty3747** [Autodesk-Forge/forge-rcdb.nodejs#79]
What is the difference between the instruction under the line "In development, the client is dynamically built by the webpack-dev-middleware, so just run:" and the instruction under the line "In production, should be done like everything that is written under the first instruction, and under the second, right? Thx

**Comment by leefsmp** [comment]
In development the client app is built in memory (no physical files produced), so when you make modifications to the client code, it is dynamically updated, no need to rebuild the full client. 

In production, your app is typically stored on a server and stays there for a while, so you need to build the files of the client app before uploading them to where ever your server is running.

**Comment by libvarun** [comment]
@marty3747  
https://webpack.js.org/guides/development/#using-webpack-dev-middleware

Please go through [concepts](https://webpack.js.org/concepts/) and [guides of webpack](https://webpack.js.org/guides/)
