### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by Mykita** [Autodesk-Forge/forge-rcdb.nodejs#8]
Hi! Nice work!

I am doing something wrong and I really want to figure it out. Here's my steps (in details):

1. I downloaded the zipped _forge-rcdb.nodejs-master_ and extracted it

2. I opened the command line using _Node.js command prompt_ and run _npm install_ from this location 

> /c/users/tgrim/downloads/forge-rcdb.nodejs-master/forge-rcdb.nodejs-master

It runs the install and then it returns this error:

`
> C:\Users\tgrim\Downloads\new1\new2\webpack>npm install
> canvas@1.6.5 install C:\Users\tgrim\Downloads\new1\new2\node_modules\canvas
> node-gyp rebuild
C:\Users\tgrim\Downloads\new1\new2\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\tgrim\Downloads\new1\new2\node_modules\canvas
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
> node-sass@3.13.1 install C:\Users\tgrim\Downloads\new1\new2\node_modules\node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":
HTTP error 404 Not Found
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.
      export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
      npm config set proxy http://example.com:8080
> node-sass@3.13.1 postinstall C:\Users\tgrim\Downloads\new1\new2\node_modules\node-sass
> node scripts/build.js
Building: C:\Program Files\nodejs\node.exe C:\Users\tgrim\Downloads\new1\new2\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\tgrim\\Downloads\\new1\\new2\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.2.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\tgrim\Downloads\new1\new2\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\tgrim\Downloads\new1\new2\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\tgrim\Downloads\new1\new2\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\tgrim\Downloads\new1\new2\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tgrim\\Downloads\\new1\\new2\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\tgrim\Downloads\new1\new2\node_modules\node-sass
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.5 (node_modules\canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgrim\AppData\Roaming\npm-cache\_logs\2017-07-26T20_56_49_072Z-debug.log
`

I would highly appreciate if you would guide me a little if you see what I am doing wrong. There's many errors here but also some error including Python.. I think I really need some guiding.

Kind regards,

**Comment by leefsmp** [comment]
Try to make sure python is installed properly on your system and PYTHON environment variable is defined and points to python.exe. Also update npm and node versions to the latests.

**Comment by Mykita** [comment]
Hi, I have updated versions to the latest and installed Python 3.6.2.
Where can I define and point the PYTHON environment variable to python.exe?
Should this be set here: C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js

**Comment by Shayneham** [comment]
Mykita, to get past this I had to download/extract GTK manually to c:\GTK

**Comment by leefsmp** [comment]
That is an issue with your dev environment not the project, so I will go ahead and close this. Cheers.
