### ISSUE TITLE
 Error when building the project

### ISSUE THREAD

**Issue by marty3747** [Autodesk-Forge/forge-rcdb.nodejs#81]
Help, please, solve the problem, I can not build the project, after executing the command “npm install” writes an error

"C: \ Users \ User \ Desktop \ forge-rcdb.nodejs-master \ node_modules \ canvas \ build \ canvas.vcxproj (20.3): Error MSB4019: imported project

C: \ Microsoft.Cpp.Default.props "was not found. Check the path in the <Import> declaration and the file is on the disk.", I enclose the logs below, thanks!

P.S Screenshots follow in order to scroll down the command line. The error is highlighted in red

![1](https://user-images.githubusercontent.com/52569199/61714067-a4839d80-ad62-11e9-9e84-1ad19e7e9b7c.png)
![2](https://user-images.githubusercontent.com/52569199/61714071-a6e5f780-ad62-11e9-95e8-1be63be3c311.png)
![3](https://user-images.githubusercontent.com/52569199/61714075-a8afbb00-ad62-11e9-98c6-cf87fa332f12.png)
![4](https://user-images.githubusercontent.com/52569199/61714081-a9e0e800-ad62-11e9-943b-c5e9c58e827f.png)
![5](https://user-images.githubusercontent.com/52569199/61714084-ab121500-ad62-11e9-8ac9-5f7670a8b70c.png)
![6](https://user-images.githubusercontent.com/52569199/61714088-acdbd880-ad62-11e9-8556-ef7087927539.png)
![6](https://user-images.githubusercontent.com/52569199/61714091-ae0d0580-ad62-11e9-8482-e38b6eef37b3.png)
![7](https://user-images.githubusercontent.com/52569199/61714097-b1a08c80-ad62-11e9-97e3-9f5ab9185cd2.png)

**Comment by dukedhx** [comment]
Install Python ^2.7 and the build tools with npm install --global --production windows-build-tools
