### ISSUE TITLE
mplementing the forge-rcdb.nodejs —> Viewing.Extension.IoT in main script

### ISSUE THREAD

**Issue by s-khini** [Autodesk-Forge/forge-rcdb.nodejs#84]
At the moment we are working on a project to implement sensor data into our autodesk forge server. However, we are not succeeding in implementing the forge-rcdb.nodejs —> Viewing.Extension.IoT in our main script. Is this still possible? Can we find a tutorial somewhere? Thank you in advance.

**Comment by dukedhx** [comment]
Yes see: 
- https://github.com/ogaryu/autodesk-forge-php-iot-sample
- https://github.com/jaimerosales/forge-aws-iot-bim360issues
- https://github.com/r06521601/IoT_Forge
And there're a few other IoT samples around
