### ISSUE TITLE
getting 401 unauthorized

### ISSUE THREAD

**Issue by gudurisaiteja** [Autodesk-Forge/forge-rcdb.nodejs#9]
getting 401 unauthorised error for endpoint
/modelderivative/v2/designdata/dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6bGVlZnNtcC1mb3JnZS9WOC5mM2Q%3D/manifest?domain=http%3A%2F%2Flocalhost%3A3000

unable to load models in UI. Any suggestions to resolve this error?

**Comment by leefsmp** [comment]
when I base64 decode it I get the following fileId: urn:adsk.objects:os.object:**leefsmp-forge**/V8.f3d. Which means you are trying to load one of my model with your own Forge credentials. This can't work. You need to use URNs of models translated with your own credentials. Keep reading the readme. Thank you.
