### ISSUE TITLE
Cannot import json files into mongodb (Autodesk-Forge/forge-rcdb.nodejs)

### ISSUE THREAD

**Issue by chadzdev** [Autodesk-Forge/forge-rcdb.nodejs#92]
Hello,
I am trying to import the 4 json files (using cmd mongoimport and Compass) into mongodb but the files seem to be bson ones (objectid is not recognizable). What shall I do with these files to make them compatible?

**Comment by dukedhx** [comment]
To get started quickly use Robo3t which supports the format of the repo out of the box.

Otherwise see README to convert to compatible formats for Compass or CLI

**Comment by chadzdev** [comment]
Thanks it worked!
