### ISSUE TITLE
Errors when running npm run dev

### ISSUE THREAD

**Issue by chadzdev** [Autodesk-Forge/forge-rcdb.nodejs#93]
I have the following settings in development.config.js:
type: 'mongo',
    connectionString: 'mongodb://localhost:27017/bim',
    dbName: 'bim',
    user: '',
    pass: '',
    dbhost: 'localhost',
    port: 27017,

when running "npm run dev" after "npm install", I get the following error in terminal. Is there anything I am setting wrong in development.config.js? I have mongodb running (I executed mongod)
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: connect ECONNREFUSED 3.229.204.112:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '3.229.204.112',
    port: 443 } }  reason:  { Error: connect ECONNREFUSED 3.229.204.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '3.229.204.112',
  port: 443 }
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: connect ECONNREFUSED 3.229.204.112:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '3.229.204.112',
    port: 443 } }  reason:  { Error: connect ECONNREFUSED 3.229.204.112:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '3.229.204.112',
  port: 443 }

**Comment by dukedhx** [comment]
if a connection string is specified that’d be used to connect the mongodb (see readme) - verify you can connect to `mongodb://localhost:27017/bim` with a mongdo client

**Comment by chadzdev** [comment]
I can connect to mongodb://localhost:27017/bim using Studio 3T or command prompt/powershell, however, I get the error mentioned in my first post when running "npm run dev" (Unhandled Rejection at: Promise Promise { ..)  this may related to nodejs not able to connect to mongodb? thanks!

**Comment by dukedhx** [comment]
then as i’ve said put your username and password in the connection string or use the config options and leave the string empty
